### ISSUE TITLE
NVDA errors when focusing on edit area

### ISSUE THREAD

**Issue by jfayre** [accessifix/nvda-for-vs-code#5]
When using the ad-on with NVDA 2019.3 beta 3. I get this error when focusing on the editor:
error executing event: gainFocus on <NVDAObjects.Dynamic_VSCodeEditorEditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x04A719D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1525, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "C:\users\jfayr\nvda-beta\userConfig\addons\NVDA-For-VS-Code\appModules\visualstudiocode.py", line 27, in event_gainFocus
    self.processLine(ti)
  File "C:\users\jfayr\nvda-beta\userConfig\addons\NVDA-For-VS-Code\appModules\visualstudiocode.py", line 48, in processLine
    self.appModule.PrevEndOffset = ti._start_endOffset
AttributeError: 'MozillaCompoundTextInfo' object has no attribute '_start_endOffset'

**Comment by pawelurbanski** [comment]
The error is fixed. I checked it with NVDA 2019.3.1 and latest VS Code as of thsi date, namely: 1.42.1.

Please head on to the releases section to download the updated add-on.
